services:
  app:
    build:
      context: .
      dockerfile: ./Api/Dockerfile 
    environment:
      "ASPNETCORE_ENVIRONMENT": ${ENV:-staging}
      "ASPNETCORE_URLS": ${APP_URL:-http://172.20.0.2:3000}
      "ConnectionStrings__EmployeesDB": ${EMPLOYEEDB:-Host=postgres;Database=EmployeesDB;Username=postgres;Password=postgres}
    ports:
      - 3000:3000
    networks:
      apps:
        ipv4_address: 172.20.0.2  
          
  db:
    image: postgres:14.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      apps:
        aliases:
          - database
          - postgres
        ipv4_address: 172.20.0.3

volumes:
  postgres-data:

networks:
  apps:
    name: apps_net
    ipam:
      config:
        - subnet: 172.20.0.0/24
          ip_range: 172.20.0.0/24
          gateway: 172.20.0.1
